---
- hosts: webservers
  become: yes
  tasks: 
  - name: i want to install git
    apt: 
      name: git
      state: present

  - name: i want to install tree
    apt:
      name: tree
      state: present

  - name: i want to install webserver on ubuntu
    apt:
      name: "{{myubuntupack}}"
      state: present

  - name : i want to install webserver on redhat
    yum:
      name: "{{myredhatpack}}"
      state: present



